language: php
os:
  - linux
dist: trusty
php:
  - '5.4'
  - '5.6'
  - '7.1'

# Database service
services:
  - mysql

# Email notifications (https://docs.travis-ci.com/user/notifications/)
notifications:
  email: false

# cache composer cache
cache:
  directories:
    - $HOME/.composer/cache

# run build against hhvm but allow them to fail
# http://docs.travis-ci.com/user/build-configuration/#Rows-That-are-Allowed-To-Fail
matrix:
  fast_finish: true
  allow_failures:
    - php: 7.1

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS todo_test;'
  - sudo apt-get -y install git zip php5-cli php5-curl

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-dist

script:
  - tests/bin/yii serve &
  - vendor/bin/codecept run
