language: php
os:
  - linux
dist: trusty
php:
  - '5.4'
  - '5.6'
  - '7.1'

# Database service
services:
  - mysql

# cache composer cache
cache:
  directories:
    - $HOME/.composer/cache

# run build against hhvm but allow them to fail
# http://docs.travis-ci.com/user/build-configuration/#Rows-That-are-Allowed-To-Fail
matrix:
  fast_finish: true
  allow_failures:
    - php: 7.1

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS todo_test;'

install:
  - composer install --no-interaction --prefer-dist

script:
  - vendor/bin/codecept run
