language: php
os:
  - linux
dist: trusty
php:
  - 5.4
  - 5.6
  - 7.1

# cache composer cache
cache:
  directories:
    - $HOME/.composer/cache

# run build against hhvm but allow them to fail
# http://docs.travis-ci.com/user/build-configuration/#Rows-That-are-Allowed-To-Fail
matrix:
  fast_finish: true
  allow_failures:
    - php: 7.1

install:
  - composer install --no-interaction --prefer-dist

script:
  - vendor/bin/codecept run
